In [56]:
import pandas as pd 
import matplotlib as plt

In [7]:
student_data = 'CSV/Students_exams_cols_cleanup.csv'

In [23]:
df = pd.read_csv(student_data)
df.head(20)

    Gender  Math Score  Reading Score  Writing Score
0   female          72             72             74
1   female          69             90             88
2   female          90             95             93
3     male          47             57             44
4     male          76             78             75
5   female          71             83             78
6   female          88             95             92
7     male          40             43             39
8     male          64             64             67
9   female          38             60             50
10    male          58             54             52
11    male          40             52             43
12  female          65             81             73
13    male          78             72             70
14  female          50             53             58
15  female          69             75             78
16    male          88             89             86
17  female          18             32             28
18    male          46             42             46
19  female          54             58             61

In [11]:
for i in df:
    print(i)

Gender
Math Score
Reading Score
Writing Score

In [24]:
df.columns = [col.lower() for col in df]
df.columns

Index(['gender', 'math score', 'reading score', 'writing score'], dtype='object')

In [42]:
for col in df.columns:
    if df[col].dtype == "object":
        df[col]=df[col].str.replace(" ","_")
df.head()

   gender  math_score  reading_score  writing_score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44
4    male          76             78             75

In [37]:
df.rename(columns= {
    'math score'     :'math_score' ,
    'reading score'  :'reading_score',
    'writing score'  :'writing_score',
},inplace=True
)
df.head(4)

   gender  math_score  reading_score  writing_score
0  female          72             72             74
1  female          69             90             88
2  female          90             95             93
3    male          47             57             44

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   gender         1000 non-null   object
 1   math_score     1000 non-null   int64
 2   reading_score  1000 non-null   int64
 3   writing_score  1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [46]:
df['math_score'].max()

100

In [49]:
df.loc[df['math_score'].idxmax()]

gender           male
math_score        100
reading_score     100
writing_score      93
Name: 149, dtype: object

In [55]:
student80_90 = df[(df["math_score"] >= 80)&(df["math_score"]<= 90 )]
student80_90

     gender  math_score  reading_score  writing_score
2    female          90             95             93
6    female          88             95             92
16     male          88             89             86
35     male          81             81             79
49     male          82             84             82
..      ...         ...            ...            ...
970  female          89            100            100
981    male          81             78             78
987    male          81             75             76
990    male          86             81             75
995  female          88             99             95

[143 rows x 4 columns]

In [53]:
print(len(student80_90))

143

In [60]:
student_df = pd.DataFrame(columns= ['statics','math','reading','writting'])

In [65]:
x = df['math_score'].max()
y = df['reading_score'].max() 
z= df['writing_score'].max()

row= {'statics':'max','math':x,'reading':y,'writting':z}
f1=pd.DataFrame.from_records([row])
student_df= pd.concat([student_df,f1],ignore_index=True)

In [68]:
x = df['math_score'].min()
y = df['reading_score'].min() 
z= df['writing_score'].min()

row = row= {'statics':'min','math':x,'reading':y,'writting':z}
f1 =pd.DataFrame.from_records([row]) 
student_df= pd.concat([student_df,f1],ignore_index=True)
student_df

  statics math reading writting
0     max  100     100      100
1     max  100     100      100
2     max  100     100      100
3     max  100     100      100
4     min    0      17       10